#!/usr/bin/env ruby
#^syntax detection

site "http://community.opscode.com/api/v1"

cookbook 'apt'
cookbook 'build-essential'
cookbook 'mysql', '5.5.3'
cookbook 'postgresql'
cookbook 'bundler'
cookbook 'ruby_build'
cookbook 'nodejs'
cookbook 'rbenv', :github => 'aminin/chef-rbenv'
cookbook 'vim'
cookbook 'mongodb'
cookbook 'nginx'
